In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)

numpy.ndarray

In [2]:
import numpy as np
a = np.array([2, 3, 4])
a
a.dtype
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [4]:
  
a = np.array([1, 2, 3, 4])  # RIGHT


In [5]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [12]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c
c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [7]:
np.zeros((3, 4))
np.ones((2, 3, 4), dtype=np.int16)

np.empty((2, 3)) 

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [8]:
np.arange(10, 30, 5)
np.arange(0, 2, 0.3)  # it accepts float arguments


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [9]:
from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

In [10]:
a = np.arange(6)                    # 1d array
print(a)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)


[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [11]:
print(np.arange(10000))
print(np.arange(10000).reshape(100, 100))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
